// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IAeroPool$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IAeroPool";
  readonly sourceName: "contracts/IPriceOracle.sol";
  readonly abi: [{"inputs":[],"name":"getReserves","outputs":[{"internalType":"uint256","name":"reserve0","type":"uint256"},{"internalType":"uint256","name":"reserve1","type":"uint256"},{"internalType":"uint256","name":"blockTimestampLast","type":"uint256"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/IPriceOracle.sol";
  readonly buildInfoId: "solc-0_8_20-e429db31a938821580db341a37fffe44d6510e4d";
};

export interface IChainlinkFeed$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IChainlinkFeed";
  readonly sourceName: "contracts/IPriceOracle.sol";
  readonly abi: [{"inputs":[],"name":"decimals","outputs":[{"internalType":"uint8","name":"","type":"uint8"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"latestRoundData","outputs":[{"internalType":"uint80","name":"roundId","type":"uint80"},{"internalType":"int256","name":"answer","type":"int256"},{"internalType":"uint256","name":"startedAt","type":"uint256"},{"internalType":"uint256","name":"updatedAt","type":"uint256"},{"internalType":"uint80","name":"answeredInRound","type":"uint80"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/IPriceOracle.sol";
  readonly buildInfoId: "solc-0_8_20-e429db31a938821580db341a37fffe44d6510e4d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IAeroPool"]: IAeroPool$Type
    ["IChainlinkFeed"]: IChainlinkFeed$Type;
    ["contracts/IPriceOracle.sol:IAeroPool"]: IAeroPool$Type
    ["contracts/IPriceOracle.sol:IChainlinkFeed"]: IChainlinkFeed$Type;
  }
}